name: Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v2
      
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          
      - name: Install dependencies
        run: composer update --prefer-dist --no-progress
        
      - name: Run test suite
        run: |
          vendor/bin/phpunit --color tests/
        env:
          # Đã chỉnh lại theo đúng tên "OC" của ní:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OC }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_SSH_PRIVATE_KEY_CONTENTS: ${{ secrets.OCI_SSH_PRIVATE_KEY_CONTENTS }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          
          # Mấy cái thông số mặc định cho Singapore:
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN || 'ap-singapore-1-AD-1' }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE || 'VM.Standard.A1.Flex' }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS || 4 }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS || 24 }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES || 1 }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
